runtime: go112

service: default

instance_class: F2
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
  - url: /.*
    secure: always
    script: auto
env_variables:
  GOOGLE_CLOUD_BUCKET_IMAGE: "qrme-image"
